Nisa addtocart feature
noviantonugroho4/nightwatchjs pull request #4
Opened 2022-08-28 17:52 UTC by chairunnisa21

<img width="230" alt="Screen Shot 2022-08-29 at 00 51 52" src="https://user-images.githubusercontent.com/110835734/187087870-87416ca4-2fe4-41ab-bbea-53f63970bdfd.png">

2022-08-29 12:14 UTC, NurMawar approved these changes

2022-08-29 14:55 UTC, zakiahafzhy approved these changes

2022-08-29 15:05 UTC, zakiahafzhy commented on .env
> +URL_shopDemoQA=https://shop.demoqa.com
ini kenapa variabel URL name nya diganti ya mba nisa?

2022-08-30 02:48 UTC, noviantonugroho4 requested changes

2022-08-30 02:48 UTC, noviantonugroho4 commented on e2e-tests/pages/home.js
> +            selector: '//div[@class="noo-product-inner noo-product-inner2"]//child::a[contains(text(), "Tokyo Talkies")]',
tolong cari cara untuk relative xpath yang lebih simple

2022-08-30 02:48 UTC, noviantonugroho4 commented on e2e-tests/pages/cart.js
> +            selector: '//*[@class="product-name"]//child::a[contains(text(), "Tokyo Talkies")]',
tolong cari cara untuk relative xpath yang lebih simple

2022-08-30 02:48 UTC, noviantonugroho4 commented on e2e-tests/pages/myAccount.js
> +            selector: '//div[@class="noo-heading-content"]//child::h1[contains(text(), "My Account")]',
tolong cari cara untuk relative xpath yang lebih simple

2022-08-30 02:48 UTC, noviantonugroho4 commented on e2e-tests/step-definitions/login.js
> +    .assert.urlEquals('https://shop.demoqa.com/my-account/')
ini kenapa tidak .assert.urlEquals() ?

value URL nya di taroh di myAccount_page.js

2022-08-30 09:25 UTC, chairunnisa21 commented on .env
> +URL_shopDemoQA=https://shop.demoqa.com
supaya lebih jelas aja kia, url web apa ^^
tapi iya sih mending kuubah ke awal aja jadi URL
thanks kia

2022-08-30 09:26 UTC, chairunnisa21 commented on e2e-tests/step-definitions/login.js
> +    .assert.urlEquals('https://shop.demoqa.com/my-account/')
iya mas, ini kemarin lupa cara assert url, siap nanti coba ku ubah mas

2022-08-31 00:13 UTC, chairunnisa21 commented on e2e-tests/step-definitions/login.js
> +    .assert.urlEquals('https://shop.demoqa.com/my-account/')
mas, untuk yang ini dalam kurungnnya kupake (url), karena pas ku coba2 kalau kosong dia error terus 🙏

2022-08-31 00:14 UTC, chairunnisa21 commented on e2e-tests/pages/myAccount.js
> +            selector: '//div[@class="noo-heading-content"]//child::h1[contains(text(), "My Account")]',
done mas

2022-08-31 00:14 UTC, chairunnisa21 commented on e2e-tests/pages/cart.js
> +            selector: '//*[@class="product-name"]//child::a[contains(text(), "Tokyo Talkies")]',
done mas

2022-08-31 00:14 UTC, chairunnisa21 commented on e2e-tests/pages/home.js
> +            selector: '//div[@class="noo-product-inner noo-product-inner2"]//child::a[contains(text(), "Tokyo Talkies")]',
done mas

2022-08-31 00:14 UTC, chairunnisa21 commented on .env
> +URL_shopDemoQA=https://shop.demoqa.com
done kia

2022-08-31 07:30 UTC, snkhomaria commented
udah oke sih mbak aku hehe, maap yaa baru bisa ngasih review

2022-09-01 22:17 UTC, noviantonugroho4 approved these changes

2022-09-01 22:17 UTC, noviantonugroho4 commented
@zakiahafzhy @snkhomaria  tolong review dan approve kalau udh ok

2022-09-02 02:03 UTC, snkhomaria approved these changes

2022-09-02 07:07 UTC, zakiahafzhy approved these changes

2022-09-02 12:42 UTC, merged